Silence errors on first uninstall

diff --git a/script/downgrade_bundler_on_old_rails b/script/downgrade_bundler_on_old_rails
--- a/script/downgrade_bundler_on_old_rails
+++ b/script/downgrade_bundler_on_old_rails
@@ -8,7 +8,8 @@ source script/functions.sh
 if ruby -e "exit(ENV['RAILS_VERSION'].scan(/\d+\.\d+.\d+/)[0].to_f < 5)"; then
   # On Rails versions less than 5, Bundler 2.0 is not supported
   echo "Warning dowgrading to older version of Bundler"
-  gem uninstall -aIx bundler
+
+  gem uninstall -aIx bundler || echo "Warning error occured removing bundler via gem"
 
   # this only works on Ruby 2.3 which is luckily the version we need to fix
   if is_ruby_23_plus; then
