Downgrade bundler on any old rails version

diff --git a/script/downgrade_bundler_on_old_rails b/script/downgrade_bundler_on_old_rails
--- a/script/downgrade_bundler_on_old_rails
+++ b/script/downgrade_bundler_on_old_rails
@@ -11,10 +11,7 @@ if ruby -e "exit(ENV['RAILS_VERSION'].scan(/\d+\.\d+.\d+/)[0].to_f < 5)"; then
 
   gem uninstall -aIx bundler || echo "Warning error occured removing bundler via gem"
 
-  # this only works on Ruby 2.3 which is luckily the version we need to fix
-  if is_ruby_23; then
-    rvm @global do gem uninstall -aIx bundler || echo "Warning error occured removing bundler via rvm"
-  fi
+  rvm @global do gem uninstall -aIx bundler || echo "Warning error occured removing bundler via rvm"
 
   gem install bundler -v '1.17.3'
 fi
