Restore bundler downgrade behaviour

diff --git a/script/downgrade_bundler_on_old_rails b/script/downgrade_bundler_on_old_rails
--- a/script/downgrade_bundler_on_old_rails
+++ b/script/downgrade_bundler_on_old_rails
@@ -9,8 +9,12 @@ if ruby -e "exit(ENV['RAILS_VERSION'].scan(/\d+\.\d+.\d+/)[0].to_f < 5)"; then
   # On Rails versions less than 5, Bundler 2.0 is not supported
   echo "Warning dowgrading to older version of Bundler"
 
-  # Delete all bundler version because we do not support Bundler 2+ below Rails 4
-  rvm @global do gem uninstall -aIx bundler || echo "Warning error occured removing bundler via rvm"
+  gem uninstall -aIx bundler || echo "Warning error occured removing bundler via gem"
+
+  # this only works on Ruby 2.3 which is luckily the version we need to fix
+  if is_ruby_23; then
+    rvm @global do gem uninstall -aIx bundler || echo "Warning error occured removing bundler via rvm"
+  fi
 
   gem install bundler -v '1.17.3'
 fi
