config simplecov coverage reporter action

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -46,6 +46,7 @@ jobs:
       - name: RUN TESTS
         timeout-minutes: 20
         run: "./bin/ci --index=${{ matrix.ci_node_index }} --total=${{ matrix.ci_node_total }} --hash=${{ github.sha }}"
+      - run: mv -v coverage/coverage.json /tmp/test_results/coverage-${{ matrix.ci_node_index }}.json
       - run: mv -v coverage/.resultset.json /tmp/test_results/resultset-${{ matrix.ci_node_index }}.json
       - name: UPLOAD TEST RESULT
         uses: actions/upload-artifact@v4
@@ -53,6 +54,7 @@ jobs:
         with:
           name: "test-report-${{ matrix.ci_node_index }}"
           path: |
+            /tmp/test_results/coverage-${{ matrix.ci_node_index }}.json
             /tmp/test_results/resultset-${{ matrix.ci_node_index }}.json
             /tmp/test_results/report-${{ matrix.ci_node_index }}.xml
           compression-level: 0 # no compression
@@ -80,6 +82,16 @@ jobs:
       - run: bundle binstubs --all
       - name: COVERAGE REPORT
         run:  bundle exec rake coverage:report
+
+      - name: Simplecov Report
+        if: success() || failure() # Recommended to forcefully comment on the PR even if RSpec returns a non-zero status code.
+        uses: shettytejas/simplecov-reporter@v1
+        with:
+          # More options as given above.
+          result-path: /tmp/aggregated_results/coverage.json
+          working-directory: /tmp/aggregated_results/
+          token: ${{ secrets.GITHUB_TOKEN }}
+
       - name: UPLOAD AGGREGATED RESULT
         uses: actions/upload-artifact@v4
         if: success() || failure()
